[application]
port = 8080

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "newsletter"

[aws]
region = "eu-west-1"
operation_timeout_secs = 7
operation_attempt_timeout_secs = 7
read_timeout_secs = 7
connect_timeout_secs = 7

[email_client]
sender_email = "newsteller@avada7.com"