[application]
port = 8080

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
database_name = "newsletter"

[aws]
region = "eu-west-1"

[email_client]
sender_email = "newsteller@avada7.com"